#!/usr/bin/python
#-*- coding: utf-8 -*-

import os
import sys, traceback

def main():

	print (str(depo_apt) + 'sonuç.............')

	cmd1 = os.system("apt-key adv --keyserver pgp.mit.edu --recv-keys ED444FF07D8D0BF6")
	cmd2 = os.system("echo '# Kali linux repositories | Added by Katoolin\ndeb http://http.kali.org/kali sana main non-free contrib\ndeb http://security.kali.org/kali-security sana/updates main contrib non-free\ndeb http://repo.kali.org/kali kali-bleeding-edge main' >> /etc/apt/sources.list")
	os.system("apt-get update -m")

	print("\033[1;36m**************************** All TOOLS *****************************\033[1;m")

	print ("\033[1;36m****************** 1) Information Gathering ******************\033[1;m")

	os.system("	apt-get install acccheck")
	os.system("	apt-get install ace-voip")
	os.system("	apt-get install amap")
	os.system("	apt-get install automater")
	os.system("	wget http://www.morningstarsecurity.com/downloads/bing-ip2hosts-0.4.tar.gz && tar -xzvf bing-ip2hosts-0.4.tar.gz && cp bing-ip2hosts-0.4/bing-ip2hosts /usr/local/bin/")
	os.system("	apt-get install braa")
	os.system("	apt-get install casefile")
	os.system("	apt-get install cdpsnarf")
	os.system("	apt-get install cisco-torch")
	os.system("	apt-get install cookie-cadger")
	os.system("	apt-get install copy-router-config")
	os.system("	apt-get install dmitry")
	os.system("	apt-get install dnmap")
	os.system("	apt-get install dnsenum")
	os.system("	apt-get install dnsmap")
	os.system("	apt-get install dnsrecon")
	os.system("	apt-get install dnstracer")
	os.system("	apt-get install dnswalk")
	os.system("	apt-get install dotdotpwn")
	os.system("	apt-get install enum4linux")
	os.system("	apt-get install enumiax")
	os.system("	apt-get install exploitdb")
	os.system("	apt-get install fierce")
	os.system("	apt-get install firewalk")
	os.system("	apt-get install fragroute")
	os.system("	apt-get install fragrouter")
	os.system("	apt-get install ghost-phisher")
	os.system("	apt-get install golismero")
	os.system("	apt-get install goofile")
	os.system("	apt-get install lbd")
	os.system("	apt-get install maltego-teeth")
	os.system("	apt-get install masscan")
	os.system("	apt-get install metagoofil")
	os.system("	apt-get install miranda")
	os.system("	apt-get install nmap")
	os.system("	apt-get install ntop")
	os.system("	apt-get install p0f")
	os.system("	apt-get install parsero")
	os.system("	apt-get install recon-ng")
	os.system("	apt-get install set")
	os.system("	apt-get install smtp-user-enum")
	os.system("	apt-get install snmpcheck")
	os.system("	apt-get install sslcaudit")
	os.system("	apt-get install sslsplit")
	os.system("	apt-get install sslstrip")
	os.system("	apt-get install sslyze")
	os.system("	apt-get install thc-ipv6")
	os.system("	apt-get install theharvester")
	os.system("	apt-get install tlssled")
	os.system("	apt-get install twofi")
	os.system("	apt-get install urlcrazy")
	os.system("	apt-get install wireshark")
	os.system("	apt-get install wol-e")
	os.system("	apt-get install xplico")
	os.system("	apt-get install ismtp")
	os.system("	apt-get install intrace")
	os.system("	apt-get install hping3")
	
	print ("\033[1;36m****************** 2) Vulnerability Analysis ******************\033[1;m")
	
	os.system("	apt-get install bbqsql")
	os.system("	apt-get install bed")
	os.system("	apt-get install cisco-auditing-tool")
	os.system("	apt-get install cisco-global-exploiter")
	os.system("	apt-get install cisco-ocs")
	os.system("	apt-get install cisco-torch")
	os.system("	apt-get install copy-router-config")
	os.system("	apt-get install doona")
	os.system("	apt-get install dotdotpwn")
	os.system("	apt-get install greenbone-security-assistant")
	os.system("	apt-get install git && git clone git://git.kali.org/packages/gsd.git")
	os.system("	apt-get install hexorbase")
	os.system("	apt-get install inguma")
	os.system("	apt-get install jsql")
	os.system("	apt-get install lynis")
	os.system("	apt-get install nmap")
	os.system("	apt-get install ohrwurm")
	os.system("	apt-get install openvas-administrator")
	os.system("	apt-get install openvas-cli")
	os.system("	apt-get install openvas-manager")
	os.system("	apt-get install openvas-scanner")
	os.system("	apt-get install oscanner")
	os.system("	apt-get install powerfuzzer")
	os.system("	apt-get install sfuzz")
	os.system("	apt-get install sidguesser")
	os.system("	apt-get install siparmyknife")
	os.system("	apt-get install sqlmap")
	os.system("	apt-get install sqlninja")
	os.system("	apt-get install sqlsus")
	os.system("	apt-get install thc-ipv6")
	os.system("	apt-get install tnscmd10g")
	os.system("	apt-get install unix-privesc-check")
	os.system("	apt-get install yersinia")
	
	print ("\033[1;36m****************** 3) Wireless Attacks ******************\033[1;m")
	
	os.system("	apt-get install aircrack-ng")
	os.system("	apt-get install asleap")
	os.system("	apt-get install bluelog")
	os.system("	apt-get install blueranger")
	os.system("	apt-get install bluesnarfer")
	os.system("	apt-get install bully")
	os.system("	apt-get install cowpatty")
	os.system("	apt-get install crackle")
	os.system("	apt-get install eapmd5pass")
	os.system("	apt-get install fern-wifi-cracker")
	os.system("	apt-get install ghost-phisher")
	os.system("	apt-get install giskismet")
	os.system("	apt-get install kalibrate-rtl")
	os.system("	apt-get install killerbee")
	os.system("	apt-get install kismet")
	os.system("	apt-get install mdk3")
	os.system("	apt-get install mfcuk")
	os.system("	apt-get install mfoc")
	os.system("	apt-get install mfterm")
	os.system("	apt-get install multimon-ng")
	os.system("	apt-get install pixiewps")
	os.system("	apt-get install reaver")
	os.system("	apt-get install redfang")
	os.system("	apt-get install rtlsdr-scanner")
	os.system("	apt-get install spooftooph")
	os.system("	apt-get install wifi-honey")
	os.system("	apt-get install wifitap")
	os.system("	apt-get install wifite")
	
	print ("\033[1;36m****************** 4) Web Applications ******************\033[1;m")
	
	os.system("	apt-get install apache-users")
	os.system("	apt-get install arachni")
	os.system("	apt-get install bbqsql")
	os.system("	apt-get install blindelephant")
	os.system("	apt-get install burpsuite")
	os.system("	apt-get install cutycapt")
	os.system("	apt-get install davtest")
	os.system("	apt-get install deblaze")
	os.system("	apt-get install dirb")
	os.system("	apt-get install dirbuster")
	os.system("	apt-get install fimap")
	os.system("	apt-get install funkload")
	os.system("	apt-get install grabber")
	os.system("	apt-get install jboss-autopwn")
	os.system("	apt-get install joomscan")
	os.system("	apt-get install jsql")
	os.system("	apt-get install maltego-teeth")
	os.system("	apt-get install padbuster")
	os.system("	apt-get install paros")
	os.system("	apt-get install parsero")
	os.system("	apt-get install plecost")
	os.system("	apt-get install powerfuzzer")
	os.system("	apt-get install proxystrike")
	os.system("	apt-get install recon-ng")
	os.system("	apt-get install skipfish")
	os.system("	apt-get install sqlmap")
	os.system("	apt-get install sqlninja")
	os.system("	apt-get install sqlsus")
	os.system("	apt-get install ua-tester")
	os.system("	apt-get install uniscan")
	os.system("	apt-get install vega")
	os.system("	apt-get install w3af")
	os.system("	apt-get install webscarab")
	os.system("	apt-get install webshag")
	os.system("	apt-get install git && git clone git://git.kali.org/packages/webslayer.git")
	os.system("	apt-get install websploit")
	os.system("	apt-get install wfuzz")
	os.system("	apt-get install wpscan")
	os.system("	apt-get install xsser")
	os.system("	apt-get install zaproxy")
	
	print ("\033[1;36m****************** 5) Sniffing & Spoofing ******************\033[1;m")
	
	os.system("	apt-get install burpsuite")
	os.system("	apt-get install dnschef")
	os.system("	apt-get install fiked")
	os.system("	apt-get install hamster-sidejack")
	os.system("	apt-get install hexinject")
	os.system("	apt-get install iaxflood")
	os.system("	apt-get install inviteflood")
	os.system("	apt-get install ismtp")
	os.system("	apt-get install git && git clone git://git.kali.org/packages/isr-evilgrade.git")
	os.system("	apt-get install mitmproxy")
	os.system("	apt-get install ohrwurm")
	os.system("	apt-get install protos-sip")
	os.system("	apt-get install rebind")
	os.system("	apt-get install responder")
	os.system("	apt-get install rtpbreak")
	os.system("	apt-get install rtpinsertsound")
	os.system("	apt-get install rtpmixsound")
	os.system("	apt-get install sctpscan")
	os.system("	apt-get install siparmyknife")
	os.system("	apt-get install sipp")
	os.system("	apt-get install sipvicious")
	os.system("	apt-get install sniffjoke")
	os.system("	apt-get install sslsplit")
	os.system("	apt-get install sslstrip")
	os.system("	apt-get install thc-ipv6")
	os.system("	apt-get install voiphopper")
	os.system("	apt-get install webscarab")
	os.system("	apt-get install wifi-honey")
	os.system("	apt-get install wireshark")
	os.system("	apt-get install xspy")
	os.system("	apt-get install yersinia")
	os.system("	apt-get install zaproxy")
	
	print ("\033[1;36m****************** 6) Maintaining Access ******************\033[1;m")
	
	os.system("	apt-get install cryptcat")
	os.system("	apt-get install cymothoa")
	os.system("	apt-get install dbd")
	os.system("	apt-get install dns2tcp")
	os.system("	apt-get install http-tunnel")
	os.system("	apt-get install httptunnel")
	os.system("	apt-get install intersect")
	os.system("	apt-get install nishang")
	os.system("	apt-get install polenum")
	os.system("	apt-get install powersploit")
	os.system("	apt-get install pwnat")
	os.system("	apt-get install ridenum")
	os.system("	apt-get install sbd")
	os.system("	apt-get install u3-pwn")
	os.system("	apt-get install webshells")
	os.system("	apt-get install weevely")
	
	print ("\033[1;36m****************** 7) Reporting Tools ******************\033[1;m")
	
	os.system("	apt-get install casefile")
	os.system("	apt-get install cutycapt")
	os.system("	apt-get install dos2unix")
	os.system("	apt-get install dradis")
	os.system("	apt-get install keepnote")
	os.system("	apt-get install magictree")
	os.system("	apt-get install metagoofil")
	os.system("	apt-get install nipper-ng")
	os.system("	apt-get install pipal")
	
	print ("\033[1;36m****************** 8) Exploitation Tools ******************\033[1;m")
	
	os.system("	apt-get install armitage")
	os.system("	apt-get install backdoor-factory")
	os.system("	apt-get install beef-xss")
	os.system("	apt-get install cisco-auditing-tool")
	os.system("	apt-get install cisco-global-exploiter")
	os.system("	apt-get install cisco-ocs")
	os.system("	apt-get install cisco-torch")
	os.system("	apt-get install crackle")
	os.system("	apt-get install jboss-autopwn")
	os.system("	apt-get install linux-exploit-suggester")
	os.system("	apt-get install maltego-teeth")
	os.system("	apt-get install set")
	os.system("	apt-get install shellnoob")
	os.system("	apt-get install sqlmap")
	os.system("	apt-get install thc-ipv6")
	os.system("	apt-get install yersinia")
	
	print ("\033[1;36m****************** 9) Forensics Tools ******************\033[1;m")
	
	os.system("	apt-get install binwalk")
	os.system("	apt-get install bulk-extractor")
	os.system("	apt-get install git && git clone git://git.kali.org/packages/capstone.git")
	os.system("	apt-get install chntpw")
	os.system("	apt-get install cuckoo")
	os.system("	apt-get install dc3dd")
	os.system("	apt-get install ddrescue")
	os.system("	apt-get install dff")
	os.system("	apt-get install git && git clone git://git.kali.org/packages/distorm3.git")
	os.system("	apt-get install dumpzilla")
	os.system("	apt-get install extundelete")
	os.system("	apt-get install foremost")
	os.system("	apt-get install galleta")
	os.system("	apt-get install guymager")
	os.system("	apt-get install iphone-backup-analyzer")
	os.system("	apt-get install p0f")
	os.system("	apt-get install pdf-parser")
	os.system("	apt-get install pdfid")
	os.system("	apt-get install pdgmail")
	os.system("	apt-get install peepdf")
	os.system("	apt-get install regripper")
	os.system("	apt-get install volat")
	
	print ("\033[1;36m****************** 10) Stress Testing ******************\033[1;m")
	
	os.system("	apt-get install dhcpig")
	os.system("	apt-get install funkload")
	os.system("	apt-get install iaxflood")
	os.system("	apt-get install git && git clone git://git.kali.org/packages/inundator.git")
	os.system("	apt-get install inviteflood")
	os.system("	apt-get install ipv6-toolkit")
	os.system("	apt-get install mdk3")
	os.system("	apt-get install reaver")
	os.system("	apt-get install rtpfloo")
	os.system("	apt-get install slowhttptes")
	os.system("	apt-get install t5")
	os.system("	apt-get install terminete")
	os.system("	apt-get install thc-ipv")
	os.system("	apt-get install thc-ssl-dos    ")
	
	print ("\033[1;36m****************** 11) Password Attacks ******************\033[1;m")
	
	os.system("	apt-get install acccheck")
	os.system("	apt-get install burpsuite")
	os.system("	apt-get install cewl")
	os.system("	apt-get install chntpw")
	os.system("	apt-get install cisco-auditing-tool")
	os.system("	apt-get install cmospwd")
	os.system("	apt-get install creddump")
	os.system("	apt-get install crunch")
	os.system("	apt-get install git && git clone git://git.kali.org/packages/dbpwaudit.git")
	os.system("	apt-get install findmyhash")
	os.system("	apt-get install gpp-decrypt")
	os.system("	apt-get install hash-identifier")
	os.system("	apt-get install hexorbase")
	os.system("	apt-get install john")
	os.system("	apt-get install johnny")
	os.system("	apt-get install keimpx")
	os.system("	apt-get install maltego-teeth")
	os.system("	apt-get install maskprocessor")
	os.system("	apt-get install multiforcer")
	os.system("	apt-get install ncrack")
	os.system("	apt-get install oclgausscrack")
	os.system("	apt-get install pack")
	os.system("	apt-get install patator")
	os.system("	apt-get install polenum")
	os.system("	apt-get install rainbowcrack")
	os.system("	apt-get install rcracki-mt")
	os.system("	apt-get install rsmangler")
	os.system("	apt-get install sqldict")
	os.system("	apt-get install statsprocessor")
	os.system("	apt-get install thc-pptp-bruter")
	os.system("	apt-get install truecrack")
	os.system("	apt-get install webscarab")
	os.system("	apt-get install wordlists")
	os.system("	apt-get install zaproxy")
	
	print ("\033[1;36m****************** 12) Reverse Engineering ******************\033[1;m")
	
	os.system("	apt-get install apktool")
	os.system("	apt-get install dex2jar")
	os.system("	apt-get install python-diStorm3")
	os.system("	apt-get install edb-debugger")
	os.system("	apt-get install jad")
	os.system("	apt-get install javasnoop")
	os.system("	apt-get install JD")
	os.system("	apt-get install OllyDbg")
	os.system("	apt-get install smali")
	os.system("	apt-get install Valgrind")
	os.system("	apt-get install YARA")
	
	print ("\033[1;36m****************** 13) Hardware Hacking ******************\033[1;m")
	
	os.system("	apt-get install android-sdk")
	os.system("	apt-get install apktool")
	os.system("	apt-get install arduino")
	os.system("	apt-get install dex2jar")
	os.system("	apt-get install sakis3g")
	os.system("	apt-get install smali")


	os.system("apt-get autoremove")

	print("Bilgisayarı yeniden başlatmanızı öneririm. Bazı toolslar tam opsiyonlu çalışmayabilir...")
	print('''

		------------Eksik Tool lar ;)

	---BlueMaho	
	---Bluepot	
	---Gqrx
	---gr-scan	
	---Winexe

	''')
	
	reb=raw_input("\033[1;36mYükleme tamamlandı Bilgisayarın yeniden başlatılması gerekiyor? (Y/N) > \033[1;m")

	if(reb=='Y'):
		print("By By --- MühendisBEY...")
		os.system("reboot")
	else:
		print("By By --- MühendisBEY...")
		os.system("exit")

if __name__ == "__main__":
	main()
